### ISSUE TITLE
Node.js Testing WG Meeting 2016-Jan-15

### ISSUE THREAD

**Issue by Trott** [nodejs/testing#1]
Will take place at:
- UTC: Friday, January 15, 2016 at 6:00:00 PM  
- Pacific Time (San Francisco): Friday, January 15, 2016 at 10:00:00 AM
- Eastern Time (Pittsburgh): Friday, January 15, 2016 at 1:00:00 PM
- Central European Time (Madrid): Friday, January 15, 2016 at 7:00:00 PM
- Western European Time (Lisbon): Friday, January 15, 2016 at 6:00:00 PM

Hangout link: https://plus.google.com/events/ctbjov1nq2pntfhvje4e7mpktd4

More to come....

**Comment by Trott** [comment]
# Agenda-ish:
- Draft docs pull request: #2
- Broken tests
  - https://github.com/nodejs/node/pull/4679
- Flaky tests
  - test-tick-processor https://github.com/nodejs/node/issues/4427
  - test-debug-no-context https://github.com/nodejs/node/issues/4343
  - For the following tests: Run a stress test to confirm? Is there an easy way to search Jenkins for recent failures?
    - sequential/test-vm-syntax-error-stderr 
    - parallel/test-tls-ticket-cluster 

## Stuff to think about:
- Unit tests (which might enable easier code coverage metrics)
- Guidelines around tests: For example, when should a file containing multiple tests be split into multiple files?
- Any current opportunities for collaboration with the Build WG?
- Porting the Python test harness to JavaScript
- Smoke testing/CITGM: What remains to be done? Should we check to see where things are with the SmokeTest WG? Does that WG officially exist? Should it be subsumed here?
- Review of existing tests: Standardize some things? Lint rules? Document how things like pummel do/don't work?
- Modularize common.js: Make it less of a junk drawer
- Benchmarking: Do we have anything automated? How do we get there? Would this overlap with the Benchmark WG or would it be distinct from their work? Does that WG still effectively exist?
- `pummel` and `debugger` seem to have a lot of not-working stuff and aren't part of CI. How can we fix that?

## Administratia:
- I can't create labels and do other things in this repo that perhaps everyone in the WG should be able to do. Who can change that?

**Comment by Trott** [comment]
It's time! https://plus.google.com/events/ctbjov1nq2pntfhvje4e7mpktd4

**Comment by orangemocha** [comment]
@Trott I think we need a different link. After you start the hangout, you can copy & paste the URL of the hangout window.

**Comment by Trott** [comment]
Oh, right, ugh! Beginner mistakes. Here, try this: https://plus.google.com/hangouts/_/hoaevent/AP36tYfNs71kiy_WrS0M_uLyD4dCQo6tPEApNQEiY944mPAcrr8y4A
