### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by Trott** [nodejs/testing#11]
- test-tick-processor: https://github.com/nodejs/node/issues/4427
- <strike>test-http-regr-gh-2928: https://github.com/nodejs/node/issues/4830</strike>
- test-repl: https://github.com/nodejs/node/issues/4823
- <strike>test-debug-no-context: https://github.com/nodejs/node/issues/4343</strike>
- <strike>test-tls-ticket-cluster</strike>
- <strike>test-vm-syntax-error-stderr</strike>
- <strike>test-cluster-shared-leak: https://github.com/nodejs/node/issues/4887</strike>
- <strike>test-http-regr-gh-2928 strikes again: https://github.com/nodejs/node/issues/5445</strike>
- test-debug-port-from-cmdline: https://github.com/nodejs/node/issues/5368

**Comment by santigimeno** [comment]
It looks like these 2 are no longer flaky:
- `test-tls-ticket-cluster`: https://github.com/nodejs/node/issues/2510
- `test-vm-syntax-error-stderr`: https://github.com/nodejs/node/issues/2660

**Comment by Trott** [comment]
Thanks, @santigimeno! Updated. (Also submitted a PR to remove them from the `.status` files where they are still marked as flaky.)

**Comment by santigimeno** [comment]
Removed `test-http-regre-gh-2998` again

**Comment by santigimeno** [comment]
Added `test-debug-port-from-cmdline`
