### ISSUE TITLE
make test-debug is not working

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/testing#12]
What is going on with this?

**Comment by cjihrig** [comment]
cc: @nodejs/testing

**Comment by Trott** [comment]
I think @jbergstroem was working on debug mode tests at some point recently (or maybe it was someone else in @nodejs/build ?). Not sure if that was distinct from `make test-debug` or if that's exactly what it was.

**Comment by jbergstroem** [comment]
@TheAlphaNerd what's the problem? Are we talking fails or that it actually doesn't work?

The jenkins job for running the debug suite over at https://ci.nodejs.org/job/jbergstroem-test-commit-debug/ is not using `make test-debug`, rather:

``` bash
$ ./configure --debug
$ V=1 make -j $(getconf _NPROCESSORS_ONLN) -C out BUILDTYPE=Debug
$ python tools/test.py -p tap --logfile test.tap \
  --mode=debug --flaky-tests=$FLAKY_TESTS_MODE \
  addons message parallel sequential
```
