### ISSUE TITLE
Test that no files in repo are too long for windows

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/testing#16]
Windows has a max path length. It would likely be a good idea for us to check that we have no files in our tree that are too long.

**Comment by joaocgreis** [comment]
This has been taken care of by a check in Jenkins: https://github.com/nodejs/build/issues/338

I'll close this issue for now, please reopen if you want to discuss other ways of doing this check.

**Comment by MylesBorins** [comment]
This should be enough for now. Can reopen if we get bit again.
