### ISSUE TITLE
Review the use of timeouts

### ISSUE THREAD

**Issue by santigimeno** [nodejs/testing#19]
I'm not sure if this deserves an issue or if there's anything actionable, but anyway...

Lately, most of the failing tests I've found: https://github.com/nodejs/node/pull/5342, https://github.com/nodejs/node/pull/5339, https://github.com/nodejs/node/pull/5129 were flaky because of the use (misuse?) of timers. It seems to me that a lot of times, the use of timers is not needed, as we can rely on the test runner timeout, and they become a source of flakiness. I could not agree more with this post from @Trott https://github.com/nodejs/node/pull/5342#issuecomment-186852033. Should we set a position on this and maybe document it somewhere?

**Comment by Trott** [comment]
I would love to get some consensus on whether arbitrary timers is (on the one hand) a valid way to provide a helpful error message to people running tests without the wrapper or (on the other hand) an anti-pattern that introduces maddening flakiness into our tests. (Spoiler alert: I think it's an anti-pattern.)

**Comment by santigimeno** [comment]
Closing in favor of https://github.com/nodejs/testing/issues/27
