### ISSUE TITLE
Experimental Jenkins instance

### ISSUE THREAD

**Issue by santigimeno** [nodejs/testing#20]
From https://github.com/nodejs/build/issues/331#issuecomment-188909950

> Due to resource constraints - mostly people's time - at this time the Build WG has not agreed to move forward with the experimental Jenkins instance. However if anybody (@nodejs/testing ?) wanted to set this up and maintain it, we would be glad to offer mentorship and a few machines.

Setting up this would help us moving forward with https://github.com/nodejs/testing/issues/3 and https://github.com/nodejs/testing/issues/7. I would like helping with this.

**Comment by jbergstroem** [comment]
@santigimeno can you pm me on IRC? (you can find me in #node-build)

**Comment by santigimeno** [comment]
Ongoing discussion for allowing access to build resources here: https://github.com/nodejs/build/pull/354

**Comment by Trott** [comment]
Closing here. This can go in the build repo if we want to keep talking about it. Feel free to comment or re-open if you think I'm taking the wrong approach here.
