### ISSUE TITLE
Test/processes that create files that aren't in temp directories

### ISSUE THREAD

**Issue by Trott** [nodejs/testing#26]
Find and eliminate tests/processes that create files that aren’t in temp directories or other expected places. (Example: make test-addons creates files in test/addons.)

/cc @TheAlphaNerd

**Comment by MylesBorins** [comment]
I'm into helping on this one.

**Comment by Trott** [comment]
Checked this in a rough way by running `make test` in one terminal window on macOS while running `sudo fs_usage -w | grep node | egrep '\bopen\b' | grep W | grep -v /dev/` in another terminal window and then lots of manual review of the results. Number of problematic files found is fewer than I expected.  PRs coming soon.

**Comment by Trott** [comment]
https://github.com/nodejs/node/pull/17808

**Comment by Trott** [comment]
https://github.com/nodejs/node/pull/17810

**Comment by Trott** [comment]
https://github.com/nodejs/node/pull/17811

And that's the last of them, as far as I can tell. Closing.
