### ISSUE TITLE
benchmark tests in CI and/or release process

### ISSUE THREAD

**Issue by Trott** [nodejs/testing#29]
The recent performance regression related to the use of `for (let...)` would be a good example of something that could be caught by performance benchmarking in CI or the release process or elsewhere.

I like that better than linting for this sort of thing because what is performant in v8 will change, but the need for performance overall will not. So a performance benchmark will do a better job of measuring the issue.

**Comment by orangemocha** [comment]
cc @nodejs/benchmarking

**Comment by mhdawson** [comment]
The benchmarking wg is looking at benchmarks overall.  Is this a suggestion to add/run a specific benchmark or that we need runs overall ?   If the former please open an issue on the benchmarking wg with the suggestion/and or requirement and we can look at adding it to what we track at: https://benchmarking.nodejs.org/.    This page has what we have in the CI so far in terms of running/collecting benchmark data: https://github.com/nodejs/benchmarking/blob/master/benchmarks/README.md

**Comment by Trott** [comment]
As the person who opened this, and because this WG is defunct, I'm going to declare https://benchmarking.nodejs.org/ adequate for my purposes. (If someone would prefer a job that actually flags performance regressions rather than relying on visual inspection or something, perhaps take the conversation up in the Build WG.)
