### ISSUE TITLE
redundant tests

### ISSUE THREAD

**Issue by bengl** [nodejs/testing#33]
I've found in my perusal of the `test` directory that there are some tests that seem to be testing the same functionality. The redundant tests could likely be removed without sacrificing the integrity of the test suite.

Would PRs removing these redundancies be worthwhile? Or should all the tests remain, to ensure nothing goes untested by mistake?

I'd submit a PR to test the waters on this, but I thought I'd ask here first to save myself some potential unnecessary work.

**Comment by cjihrig** [comment]
> Would PRs removing these redundancies be worthwhile?

I think we would have to evaluate these on a case by case basis. There are too many edge cases and historical artifacts to give a sweeping "yes" or "no" answer.

**Comment by bengl** [comment]
Fair/reasonable enough.
