### ISSUE TITLE
Someone else to chair/run this group?

### ISSUE THREAD

**Issue by Trott** [nodejs/testing#34]
I've been delinquent on scheduling meetings and taking care of business for this group the last few months. If anyone else thinks they might be willing and able to take it on, I'd be more than happy to see that happen.

It would be nice to see more stuff happen with https://github.com/nodejs/testing/blob/master/doc/ROADMAP.md

**Comment by cjihrig** [comment]
Could you define "taking care of business" other than having meetings? I think having people who care about tests is important for the project, but I think most, if not all, of the work could be done without meetings.

**Comment by Trott** [comment]
@cjihrig wrote:

>  I think most, if not all, of the work could be done without meetings.

You raise a good point. Maybe we just need an IRC channel so we can coordinate synchronously once in a while.
