### ISSUE TITLE
Invite @edsadr?

### ISSUE THREAD

**Issue by Trott** [nodejs/testing#48]
The testing group is inactive as a group that meets and plans, but is still very active in terms of getting @-notifications and responding to them on issues that involve tests. Given how much they've done with tests lately, would it make sense to invite @edsadr to be in the group?

**Comment by santigimeno** [comment]
yes please!

**Comment by edsadr** [comment]
would be really nice, happy to help here as much as I can 🙂

**Comment by Trott** [comment]
Done.
