### ISSUE TITLE
Move coverage.nodejs.org to SVGs from PNGs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/testing#49]
From https://github.com/nodejs/nodejs.org/issues/1110#issuecomment-275234548

@silverwind mentioned:

While the logos sizes are now fixed, they PNGs should really be replaced with the SVG versions I added recently. They are 1/8th of the size at no quality loss.

**Comment by silverwind** [comment]
It's a simple URL change. Replace

```
https://nodejs.org/static/images/logos/nodejs-new-white-pantone.png
```
With
```
https://nodejs.org/static/images/logo.svg
```
For light backgrounds, there's also
```
https://nodejs.org/static/images/logo-light.svg
```

**Comment by mhdawson** [comment]
Hope to get to this tomorrow

**Comment by Trott** [comment]
Coverage stuff is now in other repos. Closing this. Feel free to re-open or comment if you think I'm taking the wrong approach here.
