### ISSUE TITLE
Is this WG still active?

### ISSUE THREAD

**Issue by jasnell** [nodejs/testing#53]
Is this WG still active? If not, we should consider dechartering.

**Comment by cjihrig** [comment]
As long as we keep @nodejs/testing for mentioning, I don't think we need a chartered WG.

**Comment by santigimeno** [comment]
No, it's not and I would agree. I would like to keep the `@nodejs/testing` handle active though.

**Comment by jasnell** [comment]
Maintaining the @nodejs/testing team would certainly be doable (and preferable)

**Comment by cjihrig** [comment]
Closing in favor of the more formal #54
