### ISSUE TITLE
Dechartering this Working Group?

### ISSUE THREAD

**Issue by jasnell** [nodejs/testing#54]
The Testing Working Group has been inactive for quite some time. I have opened a proposal in the CTC repository to decharter the group. The nodejs/testing team would still exist, but this repository would be archived and the responsibilities assigned to the Testing Working Group would be folded back into the CTC's area of responsibility.

Refs: https://github.com/nodejs/CTC/pull/121

**Comment by gibfahn** [comment]
SGTM

**Comment by Trott** [comment]
No objection from me either.

**Comment by gdams** [comment]
SGTM

**Comment by mhdawson** [comment]
+1 from me.  If activity picks up it can always be re-charted.
