### ISSUE TITLE
How do we make sure tests that don't run in CI don't break

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/testing#55]
Specifically thinking suites like pummel or internet

**Comment by Trott** [comment]
For internet, I put a proposal (in an issue in the main repo, I think) to create a target for it and run it once a day like we do for node-daily-master, but limiting it to just one or two OS/platforms.

I could see doing the same for pummel.

**Comment by gibfahn** [comment]
Run them in ci...

As Trott said, we should run a complete set daily. We could probably run on all platforms, there's a lot of downtime every day in CI (as @rvagg was just mentioning elsewhere).

**Comment by Trott** [comment]
> As Trott said, we should run a complete set daily. We could probably run on all platforms, there's a lot of downtime every day in CI (as @rvagg was just mentioning elsewhere).

Probably worth checking that the `internet` tests and the `pummel` tests don't do anything we wouldn't want a whole lot of hosts doing at once. It's *probably* just fine, but you know, just in case....

**Comment by mhdawson** [comment]
Agreed we should run daily.  If specific tests do something objectionable if run by a number of machines at the same time that might be an indicator that we should either change or possibly pull out into a different group where its clear that some caution should be taken before running them.

**Comment by MylesBorins** [comment]
did we make any progress on nightly runs of these tests?

**Comment by Trott** [comment]
> did we make any progress on nightly runs of these tests?

@MylesBorins Not as far as I know. I would suggest opening an issue in the the build repo and bringing it up at a Build WG meeting.

**Comment by Trott** [comment]
This can continue in the build repo if we want to continue having the conversation. Closing. Feel free to re-open or comment if you think that's not the right approach.
