### ISSUE TITLE
Move coverage generation scripts to nodejs/build repo

### ISSUE THREAD

**Issue by maclover7** [nodejs/testing#56]
There are other assorted scripts that live there for Jenkins jobs, to me it seems like a better place to store them.

**Comment by cjihrig** [comment]
Seems fine to me, if the build team doesn't mind.

**Comment by Trott** [comment]
This repository is mostly defunct, so anything that moves us closer to being able to archive it is a good thing. So +1 from me.

**Comment by mhdawson** [comment]
I'm ok with moving them.  The test WG was more active when they were put here, but given that is no longer the case moving to build is fine with me.  

We will need to co-ordinate to avoid breaking the nightly job but it should be easy to copy over and update the job before we remove the copies in this repo.

**Comment by maclover7** [comment]
https://github.com/nodejs/build/pull/1055
