### ISSUE TITLE
Node.js setup testing

### ISSUE THREAD

**Issue by bryont** [nodejs/testing#8]
Hello,
I am working on Microsoft Nano Server.  I am looking to see if Node.JS currently has any regression test scripts we can use to further test the support of Node.JS installed on Microsoft Nano Server.

Thanks,
Bryon Trott
v-bryont@microsoft.com

**Comment by cjihrig** [comment]
@bryont we have a full test suite located in https://github.com/nodejs/node/tree/master/test. If you're working with the source repository, you can run `make test` to run a lot of the tests.

**Comment by bryont** [comment]
Hello cjihrig is there a version of make test that will run on windows?

**Comment by cjihrig** [comment]
Yes. Check out https://github.com/nodejs/node#windows.

**Comment by bryont** [comment]
<a>@Cjihrig<href=https://github.com/cjihrig /a> 

Alright, so when I attempt to run vcbuild I get the following error,

```
C:\Users\v-bryont\Desktop\node-master>vcbuild test
  File "C:\Users\v-bryont\Desktop\node-master\tools\getnodeversion.py", line 16
    print '%(major)s.%(minor)s.%(patch)s'% locals()
                                        ^
SyntaxError: invalid syntax
Cannot determine current version of Node.js
```

What exactly is going wrong?

**Comment by cjihrig** [comment]
Do you have all of the prerequisite software installed (mentioned in my previous link)? Note that the version of Python is important.

**Comment by bryont** [comment]
I had to remove Python 3.5 and it started to work,  However I am now getting errors like this:

c:\users\v-bryont\desktop\node-master\src\debug-agent.h(128): fatal error C1001: An internal error has occurred in the
compiler. [C:\Users\v-bryont\Desktop\node-master\node.vcxproj](compiler file 'f:ddvctoolscompilercxxfeslp1cconvert.cpp', line 10610)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information (src\async-wrap.cc)
c:\users\v-bryont\desktop\node-master\src\debug-agent.h(128): fatal error C1001: An internal error has occurred in the
compiler. [C:\Users\v-bryont\Desktop\node-master\node.vcxproj]

**Comment by cjihrig** [comment]
You need a C++11 capable compiler. I'm not quite sure what that translates to on Windows, but that could be what you're running into.

@nodejs/platform-windows can one of you help?

**Comment by orangemocha** [comment]
@bryont which version of the compiler are you using? VS 2015 is required.

**Comment by bryont** [comment]
I have tried on two machines, one with VS 2015, python 2.7, node.JS 4.2.3
With VS 2015 I got messages that it could not find Visual Studio.

The other computer with VS 2013 went the farthest until I got the internal Compiler errors.

Any tricks in getting VS 2015 to be seen by VCBUILD?

With only VS 2015 installed I see;
Looking for Visual Studio 2015
Looking for Visual Studio 2013
Failed to Find Visual Studio Installation.

I checked for Environment strings for 2015.  Does Visual Studio version matter?

**Comment by orangemocha** [comment]
Which edition of VS are you using? If you look inside vcbuild.bat, you'll see that it's looking for VS140COMNTOOLS. Is VS140COMNTOOLS set on your machine? If not, re-run VS 2015 setup from "programs & features", make sure that you have Visual C++ installed. If everything looks ok but VS140COMNTOOLS, try repairing the VS installation.

**Comment by bryont** [comment]
Thanks
 I finally got it building and running.  Did see one error in the test though before it 100% about EPERM: operation not permitted, symlink

Bryon

running 'cctest'
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from UtilTest
[ RUN      ] UtilTest.ListHead
[       OK ] UtilTest.ListHead (0 ms)
[----------] 1 test from UtilTest (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5 ms total)
[  PASSED  ] 1 test.
running 'python tools\test.py --mode=release  sequential parallel message -J'
=== release test-fs-symlink ===
Path: parallel/test-fs-symlink
C:\GitHub\NodeJSTest\nodejs\test\parallel\test-fs-symlink.js:29
  if (err) throw err;
           ^

Error: EPERM: operation not permitted, symlink 'C:\GitHub\NodeJSTest\nodejs\test\fixtures\cycles\root.js' -> 'C:\GitHub\NodeJSTest\nodejs\test\tmp.2\symlink1.js'
    at Error (native)
Command: C:\GitHub\NodeJSTest\nodejs\Release\node.exe C:\GitHub\NodeJSTest\nodejs\test\parallel\test-fs-symlink.js
[02:20|%  99|+ 1002|-   1]: release throw_in_line_with_tabs

**Comment by Trott** [comment]
The test failure is likely because the user running the tests does not have permissions to create symbolic links. On UNIX-like operating systems, you typically don't need any special privileges to do that, but that's not the case on Windows. At least that's my understanding.

**Comment by Trott** [comment]
Closing as it appears the original issue has been resolved. Feel free to re-open if I'm mistaken about that.

**Comment by bryont** [comment]
Hello,
Is there a way to run these tests without compiling each time?  We are looking if it is possible to move the correct files to the Nano Server were we have Node.JS setup and run the tests.  The only file that seems to run on it own after the running vcbuild.bat is cctest.exe

**Comment by joaocgreis** [comment]
The files

```
config.gypi
icu_config.gypi
Release/node.exe
Release/openssl-cli.exe
Release/cctest.exe
```

should be sufficient to run the tests. With those, you can run the tests with something like

```
vcbuild.bat release nosign x64 nobuild test-ci
```

**Comment by bryont** [comment]
Thank you for your suggestion.  Even when running with the nobuild switch.
Vcbuild.bat release x64 nobuild nosign test-ci

  I see it keeps looking for Visual studio 2015 or 2013?

The Idea is to be able to run Node.JS tests on the Nano Server with a few extra files needed as possible.

**Comment by orangemocha** [comment]
Yes, it's expected that vcbuild.bat will look for VS.

You should be able to run the tests and bypass vcbuild by doing:

`python tools\test.py --mode=release   -p tap --logfile test.tap message sequential parallel`

**Comment by bryont** [comment]
orangemocha
Thanks for you help. That command line running test.py  
was exactly what I was looking for.  I now have all the NodeJS tests running on Nano Server.

**Comment by bryont** [comment]
Hello 
I am trying to understand all the switches with test.py.  Can you run just a few tests or a single test with the --run" switch?  This says:
      help="Divide the tests in m groups (interleaved) and run tests from group n (--run=n,m with n < m)",

I am trying to figure out a way to run just a single test like:
not ok 61 test-child-process-spawn-typeerror.js

If I run that just using the test-child-process-spawn-typeerror.js file is that the same as running it from test.py?

**Comment by Trott** [comment]
`python tools/test.py --mode=release parallel/test-child-process-spawn-typeerror`

That's on OS X which is Unix-like. You may need to modify it for Windows (e.g., maybe change `/` to `\`).
